export const SEGMENT = {
  LAUNCH: 'LAUNCH',
  OCEAN: 'OCEAN',
  ISLAND: 'ISLAND',
  CARRIER_RETURN: 'CARRIER_RETURN'
};

export const TUNING = {
  WORLD_SPEED: 220,

  PLAYER: {
    START_X: 180,
    START_Y_FACTOR: 0.45,
    Y_SPEED: 240,
    X_NUDGE: 55,
    X_SMOOTH: 6,
    MIN_Y: 34
  },

  WEAPONS: {
    CANNON_COOLDOWN_MS: 150,
    BOMB_COOLDOWN_MS: 300,
    BULLET_SPEED_X: 760,
    BOMB_GRAVITY_Y: 520,
    BOMB_VELOCITY_X: 120,
    BOMB_EXPLOSION_RADIUS: 62
  },

  ENEMIES: {
    FIGHTER_SPAWN_BASE_MS: 1600,
    FIGHTER_SPAWN_MIN_MS: 700
  },

  BATTLESHIP: {
    // Tuned so it reliably takes multiple bombs to sink.
    HP: 360,
    BOMB_DAMAGE: 140,
    BULLET_DAMAGE: 4
  },

  SEGMENTS: {
    LAUNCH_MS: 3500,
    OCEAN_MS: 12000,
    ISLAND_MS: 14000,
    RETURN_MS: 9000,
    RELAUNCH_MS: 1800
  }
};
